config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root to: 'articles#index'
  resources :articles

  post "/upload_image" => "upload#upload_image", :as => :upload_image
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true

  has_one_attached :thumbnail
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true).page(params[:page]).per(20)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        setup_images()
        format.html { redirect_to @article, notice: '記事を作成しました。' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    setup_images()
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: '記事を更新しました。' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.images.purge if @article.images.attached?
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: '記事を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :thumbnail, images: [])
    end

    def setup_images
      unless params[:images_name].blank?
        # 新しい画像の実体を取得
        new_blobs = ActiveStorage::Blob.where(filename: params[:images_name].split(","))
        # 古い画像とモデルの関連付けを解除
        @article.images.detach if @article.images.attached?
        # 新しい画像をモデルと関連付け
        @article.images.attach(new_blobs)
        # モデルと関連付けされていない実体ファイルをすべて削除
        ActiveStorage::Blob.unattached.find_each(&:purge)
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery

  def new
  end

  def create
    user = User.find_by(name: session_params[:name])
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to articles_path, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to articles_path, notice: 'ログアウトしました。'
  end

  private
  def session_params
    params.require(:session).permit(:name, :password)
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  IMAGE_EXT = [".gif", ".jpeg", ".jpg", ".png"]

  def upload_image
    if params[:file]
      #拡張子チェック
      ext = File.extname(params[:file].original_filename)
      image_validation(ext)
      #保存するファイル名を作成
      file_name = "#{SecureRandom.urlsafe_base64}#{ext}"
      #DBにパラメータデータを登録
      blob = ActiveStorage::Blob.create_after_upload!(
        io: params[:file],
        filename: file_name,
        content_type: params[:file].content_type
      )
      render :json => {:link => url_for(blob)}.to_json
    end
  end

  def image_validation(ext)
      raise "許可されていない拡張子" unless IMAGE_EXT.include?(ext)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/articles/_form.html.slim
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} この記事を保存できませんでした:"
      ul
        - @article.errors.full_messages.each do |message|
          li = message
  .field.text-light
    = f.label :title
    = f.text_field :title
  .field.text-light
    = f.label :thumbnail
    = f.file_field :thumbnail, class: 'form-control'
  .field.text-light
    = f.label :content
    = f.text_area :content

  = hidden_field_tag "images_name"
  = f.submit nil, class: 'btn btn-primary mb-1'
  
  = hidden_field_tag "authenticity_token", form_authenticity_token
  = javascript_include_tag 'editor.js' 

app/views/articles/edit.html.slim
h1.text-light 記事編集

== render 'form'

== link_to '詳細', @article, class: 'btn btn-primary mr-1'
== link_to '一覧', articles_path, class: 'btn btn-primary'

app/views/articles/index.html.slim
h1.text-light 記事一覧
.row
  .col-md-9
    - @articles.each do |article|
      .card.m-3 style=("max-width: 600px;")
        .row.no-gutters href="#"
          .col-md-4.d-none.d-md-block
            img.card-img[
              style = ("max-height: 200px; max-width: 200px;")
              src = (article.thumbnail.attached? ? url_for(article.thumbnail) : '/assets/no_thumbnail.png')
            ]
          .col-md-8
            .card-body.h-100
              h4.card-title = article.title
              p.card-text = strip_tags article.content.truncate(30)
              .mt-auto.mb-0
                .row.ml-0
                  = link_to '詳細', article, class: 'btn btn-primary mr-1'
                  - if current_user
                    = link_to '編集', edit_article_path(article), class: 'btn btn-primary mr-1'
                    = link_to '削除', article, data: { confirm: '本当に削除しますか?' }, method: :delete, class: 'btn btn-primary mr-1'
                p.card-text
                  small.text-muted = '作成日時　' + article.created_at.strftime("%Y-%m-%d %H:%M")
  .col-md-3.d-none.d-md-block
    .card.m-2
      h5.font-weight-bold 記事検索
      = search_form_for @q, class: 'mb-5' do |f|
        .form-group
          = f.label :title_cont, 'タイトル', class: 'col-form-label'
        .form-group.row.m-0
          = f.search_field :title_cont, class: 'form-control'
          = f.submit class: 'btm btn-outline-primary'
      br
.mb-3
  = paginate @articles
  .text-light
    = page_entries_info @articles
br

app/views/articles/new.html.slim
h1.text-light 記事作成

== render 'form'

= link_to '一覧', articles_path, class: 'btn btn-primary'

app/views/articles/show.html.slim
.card.p-2.m-auto
  h1 = @article.title
  br
  .fr-view
    = raw @article.content
- if current_user
  => link_to '編集', edit_article_path(@article), class: 'btn btn-primary mr-1'
=< link_to '一覧', articles_path, class: 'btn btn-primary mr-1'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Blog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body style=("background: url(#{image_path'bak.jpg'}) center center / cover no-repeat fixed;")
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Blog

      ul.navbar-nav.ml-auto
          li.nav-item= link_to '記事一覧', articles_path, class: 'nav-link'
          - if current_user
            li.nav-item= link_to '記事作成', new_article_path, class: 'nav-link'
            li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
    .container.pb-5
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield